### ISSUE TITLE
Evaluation Error: Error while evaluating a Function Call, Could not find class ::facter for st2express.stackstorm.net 

### ISSUE THREAD

**Issue by bridgegh** [StorminStanley/showcase-cicd-canary#1]
James,
I am trying to use your project, showcase-cicd-canary, to get more familiar with Stackstorm. Is this project still maintained? I am getting am error with the Puppet provisoner at the end of the deployment which is preventing the puppet factor from running or gathering facts about the st2express server I assume;

 _st2express: Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::facter for st2express.stackstorm.net at /opt/puppet/shared/st2/manifests/profile/facter.pp:18:3 on node st2express.stackstorm.net
    st2express: Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::facter for st2express.stackstorm.net at /opt/puppet/shared/st2/manifests/profile/facter.pp:18:3 on node st2express.stackstorm.net_

Is there a newer project that you know of that is similar to your project to help learn Stackstorm ?
Any help would be appreciated,
Art

**Comment by arm4b** [comment]
Last commit to this showcase repo is `4` years ago. There are low chances that demo still works, considering huge changes in both StackStorm and Puppet since that.

- For learning StackStorm, I would recommend https://docs.stackstorm.com/
- For use-cases and ideas: https://stackstorm.com/category/tutorials/ (keep in mind the blog post dates)
- Forum for asking questions: https://forum.stackstorm.com/
- Community Slack chat: https://stackstorm.com/community-signup

You may also want to look at https://stackstorm.github.io/tutorials/ which is in beta state at the moment.
